apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculatorapp--deployment
  labels:
    app: calculatorapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculatorapp
  template:
    metadata:
      labels:
        app: calculatorapp
    spec:
      containers:
      - name: calculatorapp
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8000

