apiVersion: v1
kind: Service
metadata:
  name: calculatorapp
spec:
  selector:
      app: calculatorapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
#      nodePort: 31134
#  type: NodePort

